# ============================================================
# SECRETS - Sensitive configuration for AI Chatbot
# ============================================================
# CRITICAL: This file is a TEMPLATE only!
#
# Production options:
# 1. External Secrets Operator (AWS/GCP/Azure secret managers)
# 2. HashiCorp Vault with Kubernetes auth
# 3. SOPS encrypted secrets in git
# 4. Sealed Secrets controller
#
# NEVER commit actual API keys or passwords!
# ============================================================

---
apiVersion: v1
kind: Secret
metadata:
  name: {{app.name}}-secrets
  namespace: {{app.namespace}}
  labels:
    app: {{app.name}}
type: Opaque

# For development/testing only
# In production, use External Secrets or Vault
stringData:
  # ==================== LLM API Keys ====================
  # OpenAI API Key (required)
  OPENAI_API_KEY: "{{secrets.OPENAI_API_KEY}}"

  # Anthropic API Key (optional, for Claude)
  # ANTHROPIC_API_KEY: "{{secrets.ANTHROPIC_API_KEY}}"

  # ==================== Database ====================
  # PostgreSQL password
  POSTGRES_PASSWORD: "{{secrets.POSTGRES_PASSWORD}}"

  # Full connection URL
  DATABASE_URL: "{{secrets.DATABASE_URL}}"

  # Alternative: Neon serverless PostgreSQL
  # DATABASE_URL: "postgresql://user:pass@ep-xxx.aws.neon.tech/chatbot?sslmode=require"

  # ==================== Authentication ====================
  # JWT signing secret (min 32 characters)
  AUTH_SECRET: "{{secrets.AUTH_SECRET}}"

---
# ==================== EXTERNAL SECRETS EXAMPLE (AWS) ====================
# Requires: External Secrets Operator installed
# Maps AWS Secrets Manager secrets to K8s secrets
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: {{app.name}}-external-secrets
#   namespace: {{app.namespace}}
# spec:
#   refreshInterval: "1h"
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: aws-secrets-manager
#   target:
#     name: {{app.name}}-secrets
#     creationPolicy: Owner
#   data:
#   - secretKey: OPENAI_API_KEY
#     remoteRef:
#       key: chatbot/production/openai
#       property: api_key
#   - secretKey: DATABASE_URL
#     remoteRef:
#       key: chatbot/production/database
#       property: url
#   - secretKey: AUTH_SECRET
#     remoteRef:
#       key: chatbot/production/auth
#       property: secret

---
# ==================== VAULT EXAMPLE ====================
# Requires: HashiCorp Vault with Kubernetes auth
# Uses Vault Agent Injector
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: {{app.name}}-backend
#   namespace: {{app.namespace}}
#   annotations:
#     vault.hashicorp.com/agent-inject: "true"
#     vault.hashicorp.com/role: "chatbot-role"
#     vault.hashicorp.com/agent-inject-secret-openai: "secret/data/chatbot/openai"
#     vault.hashicorp.com/agent-inject-template-openai: |
#       {{`{{- with secret "secret/data/chatbot/openai" -}}
#       export OPENAI_API_KEY="{{ .Data.data.api_key }}"
#       {{- end }}`}}
