# ============================================================
# SECRETS - Event-Driven Architecture
# ============================================================
# CRITICAL: This file is a TEMPLATE only!
#
# Production options:
# 1. External Secrets Operator (AWS/GCP/Azure secret managers)
# 2. HashiCorp Vault with Kubernetes auth
# 3. SOPS encrypted secrets in git
# 4. Sealed Secrets controller
#
# NEVER commit actual passwords or API keys!
# ============================================================

---
apiVersion: v1
kind: Secret
metadata:
  name: {{app.name}}-secrets
  namespace: {{app.namespace}}
  labels:
    app: {{app.name}}
type: Opaque

# For development/testing only
# In production, use External Secrets or Vault
stringData:
  # ==================== DATABASE ====================
  # PostgreSQL password for state store
  POSTGRES_PASSWORD: "{{secrets.POSTGRES_PASSWORD}}"

  # Connection string for Dapr state store
  DAPR_STATE_CONNECTION_STRING: "host={{app.name}}-postgresql port=5432 user={{postgresql.username}} password={{secrets.POSTGRES_PASSWORD}} dbname={{postgresql.database}} sslmode=disable"

  # ==================== KAFKA (if using SASL) ====================
  # KAFKA_USERNAME: "{{secrets.KAFKA_USERNAME}}"
  # KAFKA_PASSWORD: "{{secrets.KAFKA_PASSWORD}}"

  # ==================== NOTIFICATIONS ====================
  # SMTP credentials for notification sender
  SMTP_PASSWORD: "{{secrets.SMTP_PASSWORD}}"

  # ==================== API KEYS (if needed) ====================
  # External service API keys
  # EXTERNAL_API_KEY: "{{secrets.EXTERNAL_API_KEY}}"

---
# ==================== KAFKA SECRETS (SASL/TLS) ====================
# Use for production Kafka with authentication
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{app.name}}-kafka-secrets
#   namespace: {{app.namespace}}
# type: Opaque
# stringData:
#   username: "kafka-user"
#   password: "{{secrets.KAFKA_PASSWORD}}"
#   # For mTLS
#   ca.crt: |
#     -----BEGIN CERTIFICATE-----
#     ...
#     -----END CERTIFICATE-----
#   client.crt: |
#     -----BEGIN CERTIFICATE-----
#     ...
#     -----END CERTIFICATE-----
#   client.key: |
#     -----BEGIN RSA PRIVATE KEY-----
#     ...
#     -----END RSA PRIVATE KEY-----

---
# ==================== EXTERNAL SECRETS (AWS) ====================
# Maps AWS Secrets Manager secrets to K8s secrets
# Requires: External Secrets Operator installed
#
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: {{app.name}}-external-secrets
#   namespace: {{app.namespace}}
# spec:
#   refreshInterval: "1h"
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: aws-secrets-manager
#   target:
#     name: {{app.name}}-secrets
#     creationPolicy: Owner
#   data:
#   - secretKey: POSTGRES_PASSWORD
#     remoteRef:
#       key: event-driven/production/postgres
#       property: password
#   - secretKey: SMTP_PASSWORD
#     remoteRef:
#       key: event-driven/production/smtp
#       property: password
#   - secretKey: KAFKA_PASSWORD
#     remoteRef:
#       key: event-driven/production/kafka
#       property: password

---
# ==================== VAULT SECRETS ====================
# For HashiCorp Vault integration via CSI driver
#
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: {{app.name}}-vault-secrets
#   namespace: {{app.namespace}}
# spec:
#   provider: vault
#   parameters:
#     vaultAddress: "https://vault.example.com"
#     roleName: "event-driven-role"
#     objects: |
#       - objectName: "postgres-password"
#         secretPath: "secret/data/event-driven/postgres"
#         secretKey: "password"
#       - objectName: "kafka-password"
#         secretPath: "secret/data/event-driven/kafka"
#         secretKey: "password"
#   secretObjects:
#   - secretName: {{app.name}}-secrets
#     type: Opaque
#     data:
#     - objectName: postgres-password
#       key: POSTGRES_PASSWORD
#     - objectName: kafka-password
#       key: KAFKA_PASSWORD
