# ============================================================
# SECRETS - Sensitive configuration
# ============================================================
# IMPORTANT: This file is for TEMPLATE purposes only!
#
# In production, use one of these approaches:
# 1. SOPS + Git: Encrypt secrets in git with Mozilla SOPS
# 2. External Secrets Operator: Sync from AWS/GCP/Azure secret managers
# 3. HashiCorp Vault: Dynamic secrets with Vault injector
# 4. Sealed Secrets: Bitnami sealed-secrets controller
#
# NEVER commit plaintext secrets to git!
# ============================================================

---
apiVersion: v1
kind: Secret
metadata:
  name: {{app.name}}-secrets
  namespace: {{app.namespace}}
  labels:
    app: {{app.name}}
type: Opaque

# ==================== OPTION 1: stringData (plaintext, for dev only) ====================
# K8s will base64 encode these automatically
# ONLY USE FOR LOCAL DEVELOPMENT
stringData:
  DATABASE_URL: "{{secrets.DATABASE_URL}}"
  AUTH_SECRET: "{{secrets.AUTH_SECRET}}"
  API_KEY: "{{secrets.API_KEY}}"

# ==================== OPTION 2: data (base64 encoded) ====================
# Use this in production - values must be base64 encoded
# Generate with: echo -n "your-secret" | base64
# data:
#   DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAaG9zdDo1NDMyL2Ri
#   AUTH_SECRET: eW91ci0zMi1jaGFyLXNlY3JldC1rZXktaGVyZS0xMjM=
#   API_KEY: c2steW91ci1hcGkta2V5LWhlcmU=

---
# ==================== TLS SECRET (for Ingress) ====================
# Created automatically by cert-manager if using Let's Encrypt
# Or create manually with your own certificates:
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ingress.tls.secretName}}
#   namespace: {{app.namespace}}
# type: kubernetes.io/tls
# data:
#   tls.crt: <base64-encoded-cert>
#   tls.key: <base64-encoded-key>

---
# ==================== DOCKER REGISTRY SECRET (if using private registry) ====================
# Create with:
# kubectl create secret docker-registry regcred \
#   --docker-server=ghcr.io \
#   --docker-username=<username> \
#   --docker-password=<token> \
#   --docker-email=<email>
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: regcred
#   namespace: {{app.namespace}}
# type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: <base64-encoded-docker-config>

---
# ==================== EXTERNAL SECRETS EXAMPLE (AWS) ====================
# Requires: External Secrets Operator installed
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: {{app.name}}-external-secrets
#   namespace: {{app.namespace}}
# spec:
#   refreshInterval: "1h"
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: aws-secrets-manager
#   target:
#     name: {{app.name}}-secrets
#   data:
#   - secretKey: DATABASE_URL
#     remoteRef:
#       key: /myapp/production/database
#       property: url
#   - secretKey: AUTH_SECRET
#     remoteRef:
#       key: /myapp/production/auth
#       property: secret
